#!/usr/bin/env bash
# install.sh — deploy the pi token cost tracker on any machine.
#
# One-command replication of the unified (host-owned, multi-root) token cost
# tracker. Safe to re-run: idempotent.
#
# What it does:
#   1. Copies api-equiv.sh, monthly-rollup.sh, prices.json to ~/.pi/cost-tracker/
#   2. Generates roots.conf (host always; extra roots auto-detected) if missing
#   3. Installs the @ctogg/pi-cost-counter pi extension (if `pi` is present)
#   4. Adds the `tokens` menu function to your shell rc (idempotent, marker block)
#
# Usage: ./install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="$HOME/.pi/cost-tracker"

say()  { printf '  > %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

# --- 1. scripts + prices ---
mkdir -p "$TARGET"
for f in api-equiv.sh monthly-rollup.sh prices.json; do
  cp "$SCRIPT_DIR/$f" "$TARGET/$f"
  say "copied $f"
done
chmod +x "$TARGET/api-equiv.sh" "$TARGET/monthly-rollup.sh"

# --- 2. roots.conf (generate if missing; never overwrite) ---
if [ ! -f "$TARGET/roots.conf" ]; then
  {
    echo "# Ledger roots for the pi token cost tracker (generated by install.sh)."
    echo "# One path per line; # comments; FIRST root = primary (prices.json + monthly/)."
    echo "# Runtime overrides: PI_COST_LEDGERS=/a:/b   |   PI_COST_LEDGER=/a (single)"
    echo "# Primary: host pi"
    echo "$HOME/.pi/cost-tracker"
    # auto-detect construct-cli sandbox home, add if present
    if [ -d "$HOME/.config/construct-cli/home/.pi/cost-tracker" ]; then
      echo "# construct-cli sandbox (auto-detected)"
      echo "$HOME/.config/construct-cli/home/.pi/cost-tracker"
    fi
  } > "$TARGET/roots.conf"
  say "generated roots.conf"
else
  say "roots.conf exists; left untouched"
fi

# --- 3. cost-counter extension (only if pi is installed) ---
if command -v pi >/dev/null 2>&1; then
  if pi list 2>/dev/null | grep -q 'npm:@ctogg/pi-cost-counter'; then
    say "extension @ctogg/pi-cost-counter already installed"
  else
    if pi install npm:@ctogg/pi-cost-counter >/dev/null 2>&1; then
      say "installed @ctogg/pi-cost-counter"
    else
      warn "pi install failed; run manually: pi install npm:@ctogg/pi-cost-counter"
    fi
  fi
else
  warn "pi not found; install it first, then: pi install npm:@ctogg/pi-cost-counter"
fi

# --- 4. tokens() menu into shell rc (idempotent marker block) ---
BEGIN='# >>> pi-cost-tracker tokens (managed by install.sh) >>>'
END='# <<< pi-cost-tracker tokens (managed by install.sh) <<<'
if   [ -f "$HOME/.zshrc" ];  then RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then RC="$HOME/.bashrc"
else RC="$HOME/.zshrc"; warn "no .zshrc/.bashrc found; will create $RC"
fi

# strip any prior managed block (everything from BEGIN to END inclusive)
if grep -qF "$BEGIN" "$RC" 2>/dev/null; then
  awk -v b="$BEGIN" -v e="$END" '
    $0==b {skip=1; next}
    $0==e {skip=0; next}
    !skip
  ' "$RC" > "$RC.tmp" && mv "$RC.tmp" "$RC"
  say "refreshed tokens() block in $RC"
else
  say "added tokens() block to $RC"
fi
{
  printf '\n%s\n' "$BEGIN"
  printf '# interactive menu: run "tokens" in a new shell.\n'
  # inline the function body (self-contained; no repo-path dependency at runtime)
  sed -n '/^tokens() {/,/^}$/p' "$SCRIPT_DIR/tokens.zsh"
  printf '%s\n' "$END"
} >> "$RC"

echo
say "done. open a new shell (or: source \"$RC\") and run: tokens"
say "docs: docs/AGENT-PI-cost-tracking.md"
